import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { NextAuthProvider } from "../../providers/auth";
import { QueryProvider } from "../../providers/query";
import Layout from "@/components/Layout/Layout";
import "@/app/globals.css";
import Header from "@/components/Header/Header";

const be = Be_Vietnam_Pro({
  subsets: ['vietnamese', 'latin'],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Shop Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={be.className}>
        <NextAuthProvider>
          <QueryProvider>
            <Layout>
              <Header />
              {children}
            </Layout>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
