import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { NextAuthProvider } from "../../../providers/auth";
import { QueryProvider } from "../../../providers/query";
import Layout from "@/components/Layout/Layout";
import I18nProvider from "@/providers/intl";

import "@/app/globals.css";

const be = Be_Vietnam_Pro({
  subsets: ['vietnamese', 'latin'],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Shop Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: {
    locale
  }
}: {
  children: React.ReactNode;
  params: {locale: string}
}) {
  return (
    <html lang={locale}>
      <body className={be.className}>
        <NextAuthProvider>
          <QueryProvider>     
            <I18nProvider locale={locale}>
              <Layout>
                {children}
              </Layout>         
            </I18nProvider>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
